project_name: shawk
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: "shawk"
    main: .
    binary: shawk
    ldflags:
      - -s -w
      - -X version.version={{.Version}}
      - -X version.commit={{.ShortCommit}}
      - -X version.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
changelog:
  skip: true
archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
release:
  prerelease: auto

nfpms:
  - id: "shawk"
    package_name: shawk
    file_name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
    vendor: Yuuki TSUBOUCHI
    homepage: https://github.com/yuuki/shawk
    maintainer: Yuuki TSUBOUCHI <yuki.tsubo@gmail.com>
    description: A socket-based tracing system for discovering network dependencies in distributed applications
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    empty_folders:
    files:
      "scripts/systemd/shawk.service": "/etc/systemd/system/multi-user.target.wants/shawk.service"
    config_files:
    scripts:
