project_name: transtracer
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: "ttracerd"
    main: ./cmd/ttracerd/
    binary: ttracerd
    ldflags:
      - -s -w
      - -X version.version={{.Version}}
      - -X version.commit={{.ShortCommit}}
      - -X version.date={{.Date}}
    goos:
      - linux
    goarch:
      - 386
      - amd64
  - id: "ttctl"
    main: ./cmd/ttctl/
    binary: ttctl
    ldflags:
      - -s -w
      - -X version.version={{.Version}}
      - -X version.commit={{.ShortCommit}}
      - -X version.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
changelog:
  skip: true
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
release:
  prerelease: auto
