version: "3.6"

services:
  agent:
    build: .
    depends_on:
      - db
    entrypoint: /go/bin/shawk
    command: ["--dbhost", "db"]
  db:
    image: postgres:11.7
    ports:
      - 5432
    environment:
      - POSTGRES_USER=shawk
      - POSTGRES_DB=shawk
    restart: always
    user: postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ttracer"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
